import type { PreparedQuery } from '../hydra/queries.js';
import type { HydraEvidence } from '../report/load.js';
import { shortCommit } from '../report/provenance.js';
import {
  claimsAbout,
  contradictionPartners,
  entityByName,
  evidenceForClaim,
  mentionsFrom,
  supersededByClaim,
} from '../retrieval/queries.js';
import { html, type Html } from './html.js';
import { mastheadCompact, page, panel, separator } from './layout.js';
import type { NodeIdentity } from './proof.js';

/**
 * The database page: which HydraDB, running how, and what this product asks it.
 *
 * Two things make it worth a page of its own rather than a paragraph in a
 * README. The first is that "we used HydraDB" is the easiest sentence in a
 * hackathon to write and the hardest to check, so the commit hash, the build
 * output and the raw wire responses are put where a judge can read them without
 * cloning anything. The second is that the Cypher on this page is not typed out
 * here. It is generated by calling the same functions the server calls, so it
 * cannot describe a query the product does not run.
 *
 * The last panel is the one that matters most. It lists what this project does
 * not claim about HydraDB, including the feature it would be most convenient to
 * claim, because a page of evidence with one unearned sentence in it is worth
 * less than no page at all.
 */

const OPENING = 'Every answer this product gives is a set of reads against a HydraDB '
  + 'node. There is no cache in front of it, no vector index beside it, and no model '
  + 'anywhere on the path. If the database is not running, this product returns an '
  + 'error rather than a degraded answer, which is the honest behaviour for something '
  + 'whose whole claim is that the graph is doing the work.';

function build(evidence: HydraEvidence, node: NodeIdentity): Html {
  const { provenance } = evidence;
  return html`<p class="prose">${OPENING}</p>
<table>
<tbody>
<tr><td>Commit built and run</td><td class="mono">${provenance.commit}</td></tr>
<tr><td>Version</td><td class="mono">${provenance.describe}</td></tr>
<tr><td>Compiler</td><td class="mono">${provenance.rustc}</td></tr>
<tr><td>Host</td><td class="mono">${provenance.uname}</td></tr>
<tr><td>Captured</td><td class="mono">${provenance.capturedAt}</td></tr>
<tr><td>Bolt driver</td><td class="mono">${provenance.neo4jDriver ?? 'not recorded in this capture'}</td></tr>
</tbody>
</table>
<p class="params">namespace <b>${node.namespace}</b> · graph <b>${node.graph}</b>
· cell <b>${node.cell}</b></p>
<p class="caption">Captured by the repository's own script into
artifacts/hydradb, and read from those files by this page. The base URL and the
bearer token are not on this page and cannot reach it.</p>`;
}

const INTERFACES = 'HydraDB speaks two protocols and this build was exercised on both. '
  + 'The write and the read below are raw node output, byte for byte, rather than a '
  + 'summary written here. The bookmark and the read epoch in them are what the node '
  + 'itself reported.';

function transcript(label: string, note: string, body: string): Html {
  return html`<div class="query">
<p class="query-head"><span class="n">${label}</span><span>${note}</span></p>
<pre>${body}</pre>
</div>`;
}

function interfaces(evidence: HydraEvidence): Html {
  return html`<p class="prose">${INTERFACES}</p>
${transcript('HTTP write', 'POST /query, one vertex created', evidence.smokeWrite)}
${transcript('HTTP read', 'POST /query, the same vertex back', evidence.smokeRead)}
${transcript('Bolt read', 'the same read over the Bolt port', evidence.boltRead)}
${transcript('Readiness', 'admin port, Prometheus text format', evidence.metricsReady)}
${transcript('Runtime smoke', 'the justfile target in the HydraDB tree', evidence.runtimeSmoke)}
${transcript('Object store smoke', 'persistence across restart', evidence.storeSmoke)}`;
}

const READS = 'These are the six read shapes the product issues. They are printed by '
  + 'calling the functions the server calls, with example arguments, so this list cannot '
  + 'drift from the code: if a query changes, this page changes with it. Values are '
  + 'always parameters and never string concatenation, which is why a subject named '
  + 'like a Cypher fragment is a miss rather than an injection.';

/** The example arguments. Any valid values will do; these read as the demo does. */
const SHAPES: readonly (readonly [string, string, PreparedQuery])[] = [
  ['Resolve', 'a name to an entity, or to nothing at all', entityByName('Meridian')],
  ['Claims', 'everything asserted about it, and what replaced it', claimsAbout(1)],
  ['Hop', 'claims that name a second entity, for a two step question', mentionsFrom(1)],
  ['Evidence', 'the sentences behind one claim, four hops in one pattern', evidenceForClaim(2)],
  ['Contradiction', 'claims stated to disagree with this one', contradictionPartners(2)],
  ['Revision', 'the chain this claim replaced, depth capped', supersededByClaim(2)],
];

function parameters(query: PreparedQuery): Html {
  const names = Object.keys(query.parameters);
  if (names.length === 0) return html``;
  return html`<p class="params">${names.map((name, at) => html`${at > 0 ? ' · ' : ''}${name}
<b>${String(query.parameters[name])}</b>`)}</p>`;
}

function reads(): Html {
  return html`<p class="prose">${READS}</p>
${SHAPES.map(([label, note, query]) => html`<div class="query">
<p class="query-head"><span class="n">${label}</span><span>${note}</span></p>
<pre>${query.cypher}</pre>
${parameters(query)}
</div>`)}`;
}

/**
 * The panel that decides whether the rest of the page is worth reading.
 *
 * Each entry is something this project could say, that would sound good, and
 * that the evidence does not support. Writing them down is cheaper than being
 * caught by one of them, and a judge who checks any single claim on this page
 * should find it already qualified here.
 */
const NOT_CLAIMED: readonly (readonly [string, string])[] = [
  [
    'GraphBLAS acceleration',
    'HydraDB has a GraphBLAS path. This product has not proven it runs on one, so it '
    + 'does not claim it. The reads here are ordinary Cypher over the query port, and '
    + 'no measurement in this repository isolates a GraphBLAS kernel.',
  ],
  [
    'Snapshot isolation',
    'The reads report a read epoch and the answer pages print it. That is an '
    + 'observation about what the node returned while nothing was writing to it, not a '
    + 'guarantee the store makes. A page built from several round trips can straddle a '
    + 'write, and the epoch line is where that would show.',
  ],
  [
    'Benchmarked against other databases',
    'Nothing here compares HydraDB to another database. The benchmark compares '
    + 'retrieval strategies, all of the baselines run in this process, and the only '
    + 'system on the graph is the one this product ships.',
  ],
  [
    'Production hardening',
    'One node, one namespace, one laptop, a generated corpus. No replication, no '
    + 'failover, no load beyond one browser and one benchmark process.',
  ],
];

function limits(): Html {
  return html`<p class="prose">Four things this project could say about HydraDB and does
not, with the reason in each case. They are here because a judge should be able to
check any sentence on this page and find it already qualified.</p>
<table>
<thead><tr><th>Not claimed</th><th>Why not</th></tr></thead>
<tbody>${NOT_CLAIMED.map(([claim, reason]) => html`<tr>
<td class="value">${claim}</td><td>${reason}</td>
</tr>`)}</tbody>
</table>`;
}

export function hydradbPage(evidence: HydraEvidence, node: NodeIdentity): string {
  return page({
    title: 'Lacuna | The database',
    description: 'Which HydraDB build this runs against, the raw responses it returned, '
      + 'the queries this product issues, and the claims it does not make.',
    current: '/hydradb',
    body: [
      mastheadCompact('The database'),
      panel({ index: 1, label: 'Build', heading: 'Which HydraDB this is', body: build(evidence, node) }),
      separator(),
      panel({ index: 2, label: 'Wire', heading: 'What the node returned', body: interfaces(evidence) }),
      separator(),
      panel({ index: 3, label: 'Reads', heading: 'Every query this product issues', body: reads() }),
      separator(),
      panel({ index: 4, label: 'Limits', heading: 'What this does not claim', body: limits() }),
    ],
    note: html`Evidence captured at <b>${evidence.provenance.capturedAt}</b> against
commit <b>${shortCommit(evidence.provenance)}</b>.`,
  });
}
