import { CorpusError } from './errors';
import { createRng } from './rng';
import { planThreads } from './threads';
import { buildTranscript } from './transcript';
import type { Corpus, CorpusEntity, EntityKind, Session } from './types';
import { OUT_OF_SCOPE_SUBJECTS, PEOPLE, PROJECTS, SERVICES, VENDORS } from './vocab';

/**
 * The demo corpus, generated by this code rather than written by hand, so that
 * the transcript, the gold answers and the reasons for abstaining cannot drift
 * apart. Same seed, same bytes, on any machine.
 */

export const DEFAULT_SEED = 'lacuna-demo-v1';

const ENTITY_POOLS: readonly (readonly [readonly string[], EntityKind])[] = [
  [PROJECTS, 'project'],
  [SERVICES, 'service'],
  [VENDORS, 'vendor'],
  [PEOPLE, 'person'],
];

function entityKinds(): ReadonlyMap<string, EntityKind> {
  const kinds = new Map<string, EntityKind>();
  for (const [pool, kind] of ENTITY_POOLS) {
    for (const name of pool) {
      if (kinds.has(name)) {
        throw new CorpusError(`"${name}" appears in more than one entity pool`);
      }
      kinds.set(name, kind);
    }
  }
  return kinds;
}

/**
 * The roster ingestion builds `Entity` nodes from.
 *
 * It is derived from the claims rather than from the pools, so a name that was
 * never claimed about never becomes a node. That is what keeps `out_of_scope`
 * structurally different from `never_stated` all the way into the graph: the
 * subject of an out of scope question has no node at all, while the subject of
 * a never stated question has a node with no claim on that predicate.
 */
function collectEntities(sessions: readonly Session[]): readonly CorpusEntity[] {
  const kinds = entityKinds();
  const named = new Set<string>();
  for (const session of sessions) {
    for (const message of session.messages) {
      for (const claim of message.claims) {
        named.add(claim.subject);
        if (claim.objectEntity !== null) {
          named.add(claim.objectEntity);
        }
      }
    }
  }

  return [...named].sort().map((name) => {
    const kind = kinds.get(name);
    if (kind === undefined) {
      throw new CorpusError(`claims name "${name}", which is in no entity pool`);
    }
    return { name, kind };
  });
}

export function generateCorpus(seed: string = DEFAULT_SEED): Corpus {
  const rng = createRng(seed);
  const plan = planThreads(rng);
  const transcript = buildTranscript(rng, plan);
  const corpus: Corpus = {
    seed,
    sessions: transcript.sessions,
    questions: plan.questions,
    entities: collectEntities(transcript.sessions),
    stats: transcript.stats,
  };
  validateCorpus(corpus);
  return corpus;
}

/**
 * Invariants that only hold once the text exists. Checked on every generation,
 * not only under test, because a corpus that fails these would quietly turn a
 * structural result into a lexical one.
 */
export function validateCorpus(corpus: Corpus): void {
  const roster = new Set(corpus.entities.map((entity) => entity.name));
  if (roster.size !== corpus.entities.length) {
    throw new CorpusError('the entity roster names something twice');
  }
  for (const name of OUT_OF_SCOPE_SUBJECTS) {
    if (roster.has(name)) {
      throw new CorpusError(`out of scope subject ${name} is in the entity roster`);
    }
  }

  const keys = new Set<string>();
  for (const session of corpus.sessions) {
    for (const message of session.messages) {
      if (keys.has(message.key)) {
        throw new CorpusError(`duplicate message key ${message.key}`);
      }
      keys.add(message.key);

      for (const name of OUT_OF_SCOPE_SUBJECTS) {
        if (message.text.includes(name)) {
          throw new CorpusError(`${message.key} mentions out of scope subject ${name}`);
        }
      }

      for (const span of message.spans) {
        const sliced = message.text.slice(span.start, span.end);
        if (sliced !== span.quote) {
          throw new CorpusError(
            `${message.key} span ${span.start}..${span.end} reads "${sliced}", not "${span.quote}"`,
          );
        }
      }

      const spanKeys = new Set(message.spans.map((span) => span.claimKey));
      for (const claim of message.claims) {
        if (!spanKeys.has(claim.key)) {
          throw new CorpusError(`${message.key} states ${claim.key} with no supporting span`);
        }
        if (!roster.has(claim.subject)) {
          throw new CorpusError(`${claim.key} is about "${claim.subject}", which is not in the roster`);
        }
        if (claim.objectEntity !== null && !roster.has(claim.objectEntity)) {
          throw new CorpusError(
            `${claim.key} names "${claim.objectEntity}", which is not in the roster`,
          );
        }
      }
    }
  }
}

export { CorpusError } from './errors';
export type {
  ClaimAnnotation,
  ClaimKind,
  Corpus,
  CorpusEntity,
  CorpusStats,
  EntityKind,
  EvidenceSpan,
  ExpectedAnswer,
  GoldQuestion,
  Message,
  PredicateName,
  Session,
  ThreadKind,
} from './types';
