import { CorpusError } from './errors';
import { createRng } from './rng';
import { planThreads } from './threads';
import { buildTranscript } from './transcript';
import type { Corpus } from './types';
import { OUT_OF_SCOPE_SUBJECTS } from './vocab';

/**
 * The demo corpus, generated by this code rather than written by hand, so that
 * the transcript, the gold answers and the reasons for abstaining cannot drift
 * apart. Same seed, same bytes, on any machine.
 */

export const DEFAULT_SEED = 'lacuna-demo-v1';

export function generateCorpus(seed: string = DEFAULT_SEED): Corpus {
  const rng = createRng(seed);
  const plan = planThreads(rng);
  const transcript = buildTranscript(rng, plan);
  const corpus: Corpus = {
    seed,
    sessions: transcript.sessions,
    questions: plan.questions,
    stats: transcript.stats,
  };
  validateCorpus(corpus);
  return corpus;
}

/**
 * Invariants that only hold once the text exists. Checked on every generation,
 * not only under test, because a corpus that fails these would quietly turn a
 * structural result into a lexical one.
 */
export function validateCorpus(corpus: Corpus): void {
  const keys = new Set<string>();
  for (const session of corpus.sessions) {
    for (const message of session.messages) {
      if (keys.has(message.key)) {
        throw new CorpusError(`duplicate message key ${message.key}`);
      }
      keys.add(message.key);

      for (const name of OUT_OF_SCOPE_SUBJECTS) {
        if (message.text.includes(name)) {
          throw new CorpusError(`${message.key} mentions out of scope subject ${name}`);
        }
      }

      for (const span of message.spans) {
        const sliced = message.text.slice(span.start, span.end);
        if (sliced !== span.quote) {
          throw new CorpusError(
            `${message.key} span ${span.start}..${span.end} reads "${sliced}", not "${span.quote}"`,
          );
        }
      }

      const spanKeys = new Set(message.spans.map((span) => span.claimKey));
      for (const claim of message.claims) {
        if (!spanKeys.has(claim.key)) {
          throw new CorpusError(`${message.key} states ${claim.key} with no supporting span`);
        }
      }
    }
  }
}

export { CorpusError } from './errors';
export type {
  ClaimAnnotation,
  ClaimKind,
  Corpus,
  CorpusStats,
  EvidenceSpan,
  ExpectedAnswer,
  GoldQuestion,
  Message,
  PredicateName,
  Session,
  ThreadKind,
} from './types';
