/**
 * Record a real CLI session, so the website can show one instead of drawing one.
 *
 * The landing page used to contain a hand written terminal: a workspace nobody
 * owns, a model nobody configured, a trace id that was typed rather than
 * returned, and a command list of thirteen verbs of which six exist. It carried
 * a CONCEPT PREVIEW label underneath, which is honest about it being a drawing
 * but does not make the strings true.
 *
 * This runs the CLI for real against whichever store the profile selects, keeps
 * every byte it wrote, and saves it. `web/src/landing/Cli.tsx` renders the saved
 * file. When the CLI changes, this is re-run and the site changes with it, which
 * is the only way a screenshot of a product stays true to the product.
 *
 * `isTTY` is set to true deliberately. That is not a lie about the run, it is
 * the difference between what the terminal shows a person and what a pipe
 * shows a program, and the page is a picture of the first one. The mark is part
 * of that output for the same reason.
 *
 *   LACUNA_PROFILE=cloud npx tsx scripts/capture-cli.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { main } from '../src/cli/main.js';

const ROOT = new URL('../', import.meta.url);
const OUT_DIR = new URL('artifacts/cli/', ROOT);

/** Width of the recording. 80 is the terminal every terminal can be. */
const COLUMNS = 80;

/**
 * The four commands the page shows, in the order a person would run them:
 * where am I pointed, is it healthy, ask something with a history behind it,
 * then ask something the sessions never settled.
 */
const RUNS: readonly (readonly string[])[] = [
  ['status'],
  ['ask', 'Bellwether', 'beta_partner'],
  ['explain', 'Bellwether', 'beta_partner'],
  ['ask', 'Redshank', 'launch_date'],
];

interface Capture {
  readonly argv: readonly string[];
  readonly exitCode: number;
  readonly stdout: string;
  readonly stderr: string;
}

async function record(argv: readonly string[]): Promise<Capture> {
  let stdout = '';
  let stderr = '';
  const exitCode = await main(argv, {
    out: (text) => { stdout += text; },
    err: (text) => { stderr += text; },
    isTTY: true,
    columns: COLUMNS,
  });
  return { argv, exitCode, stdout, stderr };
}

/** Colour is an accent in this CLI, so the recording keeps the words only. */
const ESCAPE = String.fromCharCode(27);
function stripAnsi(text: string): string {
  return text
    .split(`${ESCAPE}[`)
    .map((part, index) => (index === 0 ? part : part.slice(part.indexOf('m') + 1)))
    .join('');
}

const captures: Capture[] = [];
for (const argv of RUNS) captures.push(await record(argv));

const failed = captures.filter((capture) => capture.exitCode !== 0);
if (failed.length > 0) {
  for (const capture of failed) {
    process.stderr.write(`lacuna ${capture.argv.join(' ')} exited ${capture.exitCode}\n`);
    process.stderr.write(capture.stderr);
  }
  process.exit(1);
}

const session = captures
  .map((capture) => `$ lacuna ${capture.argv.join(' ')}\n\n${stripAnsi(capture.stdout).trimEnd()}`)
  .join('\n\n');

const widest = Math.max(...session.split('\n').map((line) => line.length));

mkdirSync(fileURLToPath(OUT_DIR), { recursive: true });
writeFileSync(fileURLToPath(new URL('session.txt', OUT_DIR)), `${session}\n`, 'utf8');
writeFileSync(
  fileURLToPath(new URL('session.json', OUT_DIR)),
  `${JSON.stringify(
    {
      recorded: new Date().toISOString().slice(0, 10),
      profile: process.env['LACUNA_PROFILE'] ?? 'default',
      columns: COLUMNS,
      widestLine: widest,
      runs: captures.map((capture) => ({
        command: `lacuna ${capture.argv.join(' ')}`,
        exitCode: capture.exitCode,
        lines: stripAnsi(capture.stdout).trimEnd().split('\n').length,
      })),
    },
    null,
    2,
  )}\n`,
  'utf8',
);

/**
 * The same bytes again as a module the site imports.
 *
 * `artifacts/cli/session.txt` is the evidence and this is the copy the bundler
 * can reach: `web/` is its own Vite root and importing text from outside it
 * means widening the allowed filesystem, which is a larger change than writing
 * the file twice. Generated, committed, and never edited by hand.
 */
writeFileSync(
  fileURLToPath(new URL('web/src/landing/cli-session.ts', ROOT)),
  [
    '// Generated by scripts/capture-cli.ts. Do not edit.',
    '//',
    '// A real run of the CLI, recorded against the store named in the output.',
    '// Regenerate with: LACUNA_PROFILE=cloud npx tsx scripts/capture-cli.ts',
    `// Recorded ${new Date().toISOString().slice(0, 10)}.`,
    '',
    `export const CLI_SESSION = ${JSON.stringify(session)};`,
    '',
  ].join('\n'),
  'utf8',
);

process.stdout.write(`${session}\n\n`);
process.stdout.write(`widest line ${widest} of ${COLUMNS} columns\n`);
process.stdout.write('artifacts/cli/session.txt written.\n');
process.stdout.write('web/src/landing/cli-session.ts written.\n');
