import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';

import { generateCorpus } from '../src/corpus/index.js';
import { buildPlan } from '../src/ingest/plan.js';

/**
 * One file that owns every number this repository says about itself.
 *
 * The reason it exists is that the numbers drifted. Test counts, corpus sizes
 * and the deployment's own description were stated in a dozen documents and
 * updated in some of them, so a reader comparing two files found two answers
 * and had no way to tell which was current. An external audit found several of
 * those and was right about all but one.
 *
 * So the values are read from the artifacts that produced them rather than
 * typed, and anything with no artifact behind it is recorded as `null` with a
 * reason rather than filled in from memory. A null here is the honest state of
 * a measurement that has not been taken.
 *
 *   npx tsx scripts/release-manifest.ts
 */

const OUT = 'artifacts/release/current.json';
const PRODUCTION = 'https://lacuna-five.vercel.app';
const VERIFICATION = 'artifacts/verification/2026-08-19';

function git(...args: readonly string[]): string {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

function readIf(path: string): string | null {
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}

function json<T>(path: string): T | null {
  const text = readIf(path);
  if (text === null) return null;
  try {
    return JSON.parse(text) as T;
  } catch {
    return null;
  }
}

/** `Tests  1189 passed (1189)` out of a vitest transcript. */
function testCount(path: string): { tests: number; files: number } | null {
  const text = readIf(path);
  if (text === null) return null;
  const tests = /Tests\s+(\d+)\s+passed/.exec(text);
  const files = /Test Files\s+(\d+)\s+passed/.exec(text);
  if (tests?.[1] === undefined || files?.[1] === undefined) return null;
  return { tests: Number(tests[1]), files: Number(files[1]) };
}

function sha256Of(path: string): string | null {
  if (!existsSync(path)) return null;
  return createHash('sha256').update(readFileSync(path)).digest('hex');
}

const corpus = generateCorpus();
const plan = buildPlan(corpus);

const unit = testCount(`${VERIFICATION}/unit.txt`);
const contract = testCount(`${VERIFICATION}/contract.txt`);

interface Curve {
  readonly historyGrowth: number;
  readonly contextGrowth: number;
  readonly points: readonly {
    readonly sessions: number;
    readonly estimatedTokens: number;
    readonly correct: number;
    readonly falseAnswers: number;
    readonly meanContextTokens: number;
  }[];
}
const curve = json<Curve>('artifacts/scale/curve.json');
const largest = curve?.points[curve.points.length - 1] ?? null;

interface Soak {
  readonly requests?: number;
  readonly concurrency?: number;
  readonly throughputPerSecond?: number;
  readonly p50?: number;
  readonly p95?: number;
  readonly p99?: number;
  readonly failures?: number;
}
const soak = json<Soak>('artifacts/soak/soak.json');

const VIDEO = 'video/hyperframes/renders/draft/lacuna-demo-DRAFT-2026-08-19.mp4';

const manifest = {
  generatedAt: new Date().toISOString(),
  note:
    'Generated by scripts/release-manifest.ts from committed artifacts. A null is a '
    + 'measurement that has not been taken, not a number withheld.',

  release: {
    sha: git('rev-parse', 'HEAD'),
    shortSha: git('rev-parse', '--short', 'HEAD'),
    branch: git('rev-parse', '--abbrev-ref', 'HEAD'),
    productionUrl: PRODUCTION,
    repository: 'https://github.com/vaibhav4046/lacuna',
    license: 'Apache-2.0',
  },

  tests: {
    unit: unit?.tests ?? null,
    unitFiles: unit?.files ?? null,
    contract: contract?.tests ?? null,
    contractFiles: contract?.files ?? null,
    totalWithNode: unit === null || contract === null ? null : unit.tests + contract.tests,
    source: VERIFICATION,
  },

  corpus: {
    seed: corpus.seed,
    sessions: corpus.stats.sessions,
    messages: corpus.stats.messages,
    characters: corpus.stats.characters,
    estimatedTokens: corpus.stats.estimatedTokens,
    claims: plan.counts.vertices.Claim,
    entities: plan.counts.vertices.Entity,
    goldQuestions: corpus.questions.length,
  },

  evaluation: {
    // The generated evaluation, which is not a public benchmark and is labelled
    // that way everywhere it appears.
    sampleSize: largest?.correct === undefined ? null : 64,
    correct: largest?.correct ?? null,
    falseAnswers: largest?.falseAnswers ?? null,
    meanContextTokens: largest?.meanContextTokens ?? null,
    kind: 'generated',
    officialLongMemEvalScore: null,
    officialLongMemEvalNote:
      'No LongMemEval number exists. docs/BENCHMARK_LONGMEMEVAL.md records why, '
      + 'including that the extractor does not read that domain.',
  },

  scaleCurve: curve === null ? null : {
    historyGrowth: curve.historyGrowth,
    contextGrowth: curve.contextGrowth,
    smallestTokens: curve.points[0]?.estimatedTokens ?? null,
    largestTokens: largest?.estimatedTokens ?? null,
    points: curve.points.length,
    caveat: 'The claim set is held fixed at every size, so this measures that history volume '
      + 'does not reach the answer path, not behaviour as claims grow.',
  },

  soak: soak === null ? null : {
    requests: soak.requests ?? null,
    concurrency: soak.concurrency ?? null,
    throughputPerSecond: soak.throughputPerSecond ?? null,
    p50: soak.p50 ?? null,
    p95: soak.p95 ?? null,
    p99: soak.p99 ?? null,
    failures: soak.failures ?? null,
  },

  hydra: {
    productionProfile: 'cloud',
    productionDatabase: 'lacuna',
    productionCollection: 'backend',
    benchmarkProfile: 'self-hosted node',
    pinnedVersion: 'v0.1.1',
    pinnedCommit: '02a40025d2d57e97ab2754c8256219cdbfeab379',
  },

  surfaces: {
    web: 'live',
    cli: 'live, against either profile',
    mcpStdio: 'live',
    mcpHttp: `live at ${PRODUCTION}/mcp, no key`,
    googleAuth: 'configured and verified',
    slackAuth: 'not built',
    githubAuth: 'not built',
    ingestion: 'one path, signed in, paste a transcript',
    voice: 'not configured, and the screen says so',
    passwordReset: 'not configured, and the page says so',
  },

  video: {
    path: existsSync(VIDEO) ? VIDEO : null,
    bytes: existsSync(VIDEO) ? statSync(VIDEO).size : null,
    sha256: sha256Of(VIDEO),
    durationSeconds: null,
    url: null,
    state: 'draft, to be recaptured from the frozen release',
  },

  submission: {
    state: 'not submitted',
    deadline: '2026-08-20T23:59:00-07:00',
  },
} as const;

mkdirSync('artifacts/release', { recursive: true });
writeFileSync(OUT, `${JSON.stringify(manifest, null, 2)}\n`);

process.stdout.write(`${OUT} written.\n\n`);
process.stdout.write(`sha        ${manifest.release.shortSha}\n`);
process.stdout.write(`tests      ${manifest.tests.unit} unit + ${manifest.tests.contract} contract = ${manifest.tests.totalWithNode}\n`);
process.stdout.write(`corpus     ${manifest.corpus.sessions} sessions, ${manifest.corpus.estimatedTokens} tokens, ${manifest.corpus.claims} claims\n`);
process.stdout.write(`evaluation ${manifest.evaluation.correct}/${manifest.evaluation.sampleSize}, ${manifest.evaluation.meanContextTokens} ctx tokens\n`);
process.stdout.write(`video      ${manifest.video.state}\n`);
